# Generated by Django 3.0.8 on 2020-09-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True)),
                ('timer', models.DurationField(blank=True)),
                ('personnel', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('school', models.CharField(max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='checkmate/user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checker', models.BooleanField(default=False, verbose_name='체커')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='classroom_set',
            field=models.ManyToManyField(blank=True, through='attendance.Role', to='attendance.Classroom'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attendance', models.BooleanField(default=False)),
                ('time_out', models.DurationField(blank=True, default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Profile')),
            ],
        ),
    ]
