# Generated by Django 3.0.8 on 2020-10-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['classroom', 'user']},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name', 'uuid']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['classroom', 'user', 'is_checker']},
        ),
    ]
