# Generated by Django 3.0.8 on 2020-10-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20201001_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['classroom', 'is_checker', '-user']},
        ),
    ]
