# Generated by Django 3.0.8 on 2020-10-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20201004_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='timer',
            field=models.DurationField(default=300),
        ),
    ]
