# Generated by Django 3.0.8 on 2020-10-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20201004_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='guest', max_length=20, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_attendance',
            field=models.BooleanField(default=False, verbose_name='출석 여부'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.DurationField(blank=True, default=0, verbose_name='자리비운 시간'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='desc',
            field=models.TextField(blank=True, verbose_name='소개'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=30, verbose_name='클래스룸 명'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='personnel',
            field=models.PositiveIntegerField(default=10, verbose_name='제한인원'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='timer',
            field=models.DurationField(default=300, verbose_name='자리비움 시간'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=20, verbose_name='소속 학교or기관'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='학번or학년/반'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='checkmate/user', verbose_name='얼굴 정면 사진'),
        ),
    ]
