# Generated by Django 3.0.8 on 2020-10-23 17:28

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20201006_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=20, verbose_name='소속학교/학과 or 기관'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='학번 or 학년/반'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='user', verbose_name='얼굴 정면 사진'),
        ),
        migrations.CreateModel(
            name='ClassroomEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, verbose_name='요청 메세지')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Profile')),
            ],
        ),
    ]
